/* Unified CRUD workspace for the operational admin sections. */
const entity = new URLSearchParams(location.search).get('entity') || 'teams';
let profile, activeTournament, records = [], editing = null;
const defs = {
  tournaments:{title:'Tournaments', table:'tournaments', fields:[['name','Tournament name','text'],['description','Description','textarea'],['game','Game','text'],['mode','Game mode','text'],['status','Status','select:upcoming|live|completed|cancelled'],['start_date','Tournament date & time','datetime-local'],['total_team_slots','Maximum teams','number'],['entry_fee','Entry fee','number'],['youtube_video_id','YouTube live ID','text'],['youtube_channel_url','YouTube channel URL','url'],['is_active','Show on website','checkbox']]},
  teams:{title:'Teams',table:'teams',fields:[['team_name','Team name','text'],['captain_name','Captain','text'],['status','Status','select:approved|rejected|disqualified']]},
  players:{title:'Players',table:'players',fields:[['name','Player name','text'],['free_fire_uid','Free Fire UID','text'],['team_id','Team','team'],['is_captain','Captain','checkbox'],['kills','Kills','number'],['headshots','Headshots','number'],['matches_played','Matches played','number'],['status','Status','select:active|banned|inactive']]},
  matches:{title:'Matches',table:'matches',fields:[['match_number','Match number','number'],['label','Label','text'],['map','Map','text'],['mode','Mode','text'],['scheduled_time','Scheduled time','datetime-local'],['status','Status','select:upcoming|checkin|room_open|live|completed|cancelled']]},
  leaderboard:{title:'Leaderboard',table:'leaderboard',fields:[['team_id','Team','team'],['matches_played','Matches played','number'],['kills','Kills','number'],['placement_points','Placement points','number'],['total_points','Total points','number'],['rank','Rank','number'],['is_published','Publish on website','checkbox']]},
  rooms:{title:'Room Control',table:'room_details',fields:[['match_id','Match','match'],['room_id','Room ID','text'],['room_password','Room password','text'],['map','Map','text'],['status','Room status','select:scheduled|open|closed'],['is_published','Publish room','checkbox']]},
  announcements:{title:'Announcements',table:'announcements',fields:[['title','Title','text'],['message','Message','textarea'],['priority','Priority','select:normal|important|urgent'],['is_pinned','Pin announcement','checkbox'],['published_at','Schedule / publish at','datetime-local'],['is_published','Publish now','checkbox']]},
  rules:{title:'Tournament Rules',table:'tournament_rules',fields:[['section_title','Section title','text'],['items','Rules (one per line)','lines'],['sort_order','Display order','number']]}
};
const def = defs[entity] || defs.teams;
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg,bad=false){const e=document.createElement('div');e.className='toast'+(bad?' err':'');e.textContent=msg;$('#toastStack').append(e);setTimeout(()=>e.remove(),3500)}
async function init(){profile=await requireAdmin();if(!profile)return;$('#adminUserLabel').textContent=`${profile.email} · ${profile.role.toUpperCase()}`;$('#logoutBtn').onclick=()=>logAudit('Admin Logout',profile.id,null).finally(adminLogout);$('#pageTitle').textContent=def.title;document.title=`${def.title} — Adan FF Admin`;document.querySelectorAll('.admin-nav a').forEach(a=>a.classList.toggle('active',a.href===location.href));const r=await window.db.from('tournaments').select('id').eq('is_active',true).maybeSingle();activeTournament=r.data; if(!activeTournament && entity!=='tournaments'){$('#notice').innerHTML='<p class="admin-loading">Create and activate a tournament first.</p>'} await load(); $('#newBtn').onclick=()=>openEditor();$('#closeEditor').onclick=closeEditor;$('#editor').onclick=e=>{if(e.target===$('#editor'))closeEditor()};$('#recordForm').onsubmit=save;$('#search').oninput=render; subscribe();}
async function load(){let q=window.db.from(def.table).select('*').order('created_at',{ascending:false});if(entity!=='tournaments'&&activeTournament)q=q.eq('tournament_id',activeTournament.id);const {data,error}=await q;if(error){toast(error.message,true);return}records=data||[];render()}
function columns(){return def.fields.slice(0,5).map(f=>f[0])}
function display(r,k){if(k==='team_id')return r.team_name||r.team_id; if(k==='items')return Array.isArray(r.items)?r.items.join('; '):'';return typeof r[k]==='boolean'?(r[k]?'Yes':'No'):r[k]??'—'}
function render(){const q=$('#search').value.toLowerCase();const rows=records.filter(r=>JSON.stringify(r).toLowerCase().includes(q));const cols=columns();$('#thead').innerHTML='<tr>'+cols.map(k=>`<th>${esc(def.fields.find(f=>f[0]===k)[1])}</th>`).join('')+'<th>Actions</th></tr>';$('#tbody').innerHTML=rows.length?rows.map(r=>`<tr>${cols.map(k=>`<td>${esc(display(r,k))}</td>`).join('')}<td class="manage-actions"><button data-edit="${r.id}">Edit</button><button data-delete="${r.id}" class="danger">Delete</button>${entity==='teams'?`<button data-status="${r.id}" data-value="approved">Approve</button><button data-status="${r.id}" data-value="rejected">Reject</button><button data-status="${r.id}" data-value="disqualified">DQ</button>`:''}</td></tr>`).join(''):'<tr><td colspan="8" class="admin-loading">No records found.</td></tr>';$('#tbody').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(records.find(r=>r.id===b.dataset.edit)));$('#tbody').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete));$('#tbody').querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>quickStatus(b.dataset.status,b.dataset.value));}
async function options(type,value){if(type==='team'){const {data=[]}=await window.db.from('teams').select('id,team_name').eq('tournament_id',activeTournament.id);return `<select name="team_id">${data.map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${esc(x.team_name)}</option>`).join('')}</select>`}if(type==='match'){const {data=[]}=await window.db.from('matches').select('id,label').eq('tournament_id',activeTournament.id);return `<select name="match_id"><option value="">No match assigned</option>${data.map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${esc(x.label)}</option>`).join('')}</select>`}}
async function openEditor(record=null){editing=record;$('#editorTitle').textContent=record?'Edit '+def.title.slice(0,-1):'Create '+def.title.slice(0,-1);let html='';for(const [key,label,type] of def.fields){let v=record?.[key]??(type==='checkbox'?false:'');if(type==='team'||type==='match'){html+=`<div class="login-field"><label>${label}</label>${await options(type,v)}</div>`;continue}if(type==='textarea'||type==='lines') html+=`<div class="login-field"><label>${label}</label><textarea name="${key}">${esc(type==='lines'&&Array.isArray(v)?v.join('\n'):v)}</textarea></div>`;else if(type.startsWith('select:'))html+=`<div class="login-field"><label>${label}</label><select name="${key}">${type.slice(7).split('|').map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}</select></div>`;else if(type==='checkbox')html+=`<label class="check-field"><input type="checkbox" name="${key}" ${v?'checked':''}> ${label}</label>`;else {if(type==='datetime-local'&&v)v=new Date(v).toISOString().slice(0,16);html+=`<div class="login-field"><label>${label}</label><input name="${key}" type="${type}" value="${esc(v)}"></div>`}}$('#fields').innerHTML=html;$('#editor').classList.add('open')}
function closeEditor(){$('#editor').classList.remove('open');editing=null}
async function save(e){e.preventDefault();const fd=new FormData(e.target), p={};for(const [key,,type] of def.fields){let v=type==='checkbox'?fd.get(key)==='on':fd.get(key);if(type==='number')v=v===''?0:Number(v);if(type==='lines')v=String(v||'').split('\n').map(x=>x.trim()).filter(Boolean);if(type==='datetime-local')v=v?new Date(v).toISOString():null;p[key]=v}if(entity!=='tournaments'){if(!activeTournament){toast('An active tournament is required.',true);return}p.tournament_id=activeTournament.id}if(entity==='leaderboard'){p.total_points=Number(p.total_points)||Number(p.kills||0)+Number(p.placement_points||0)}let res=editing?await window.db.from(def.table).update(p).eq('id',editing.id):await window.db.from(def.table).insert([p]);if(res.error){toast(res.error.message,true);return}await logAudit(editing?`${def.title} Updated`:`${def.title} Created`,editing?.id||null,p);toast('Saved. Realtime clients are updated.');closeEditor();await load()}
async function remove(id){if(!confirm('Delete this record? This cannot be undone.'))return;const {error}=await window.db.from(def.table).delete().eq('id',id);if(error){toast(error.message,true);return}await logAudit(`${def.title} Deleted`,id,null);toast('Deleted.');load()}
async function quickStatus(id,status){const {error}=await window.db.from('teams').update({status}).eq('id',id);if(error){toast(error.message,true);return}await logAudit('Team Status Changed',id,{status});load()}
function subscribe(){window.db.channel('manage-'+entity).on('postgres_changes',{event:'*',schema:'public',table:def.table},load).subscribe()}
init();
